from __future__ import annotations

class ViewProxy:
    @property
    def id(self) -> str: ...
    @property
    def view_class(self) -> str: ...

class AssetProxy(str):
    @property
    def id(self) -> str: ...
    @property
    def entity_class(self) -> str | None: ...
    def connect(self, *nodes: str) -> AssetProxy: ...

