from __future__ import annotations

from typing import Any, ClassVar, Dict, List, Optional, TypeVar, Union
from pathlib import Path
from ear.entity import Entity
from ear.entity_class import EntityClass
from ear.schema_manifest import SchemaManifest
from cesdm.proxy import AssetProxy
from cesdm.generated_proxies import (
    AssetLifecycleViewProxy,
    AssetLocationViewProxy,
    AssetPlanningViewProxy,
    BusLocationViewProxy,
    CarrierDomainProxy,
    ControllerViewAVRAC1AProxy,
    ControllerViewAVRIEEET1Proxy,
    ControllerViewAVRSEXSProxy,
    ControllerViewAVRST1AProxy,
    ControllerViewGOVGGOV1Proxy,
    ControllerViewGOVHYGOVProxy,
    ControllerViewGOVIEEEG1Proxy,
    ControllerViewPSSPSS2AProxy,
    ControllerViewPSSPSS2BProxy,
    ControllerViewPSSSTAB1Proxy,
    ConversionDispatchViewProxy,
    ConversionPortProxy,
    ConversionUnitProxy,
    ConverterTypeProxy,
    DemandDispatchViewProxy,
    DemandPowerFlowViewProxy,
    DemandUnitDispatchResultViewProxy,
    DemandUnitProxy,
    DispatchRunRecordProxy,
    DynamicRunRecordProxy,
    ElectricalBusPowerFlowResultViewProxy,
    ElectricalBusPowerFlowViewProxy,
    ElectricalBusProxy,
    EnergyCarrierProxy,
    EnergySystemModelProxy,
    EnergyTechnologyTypeProxy,
    ExternalSupplyDispatchViewProxy,
    ExternalSupplyProxy,
    GasBusProxy,
    GenerationDispatchViewProxy,
    GenerationUnitDispatchResultViewProxy,
    GenerationUnitPowerFlowResultViewProxy,
    GenerationUnitProxy,
    GeneratorDynamicResultViewProxy,
    GeneratorDynamicViewSubtransientProxy,
    GeneratorPowerFlowViewProxy,
    GeneratorTypeProxy,
    GeographicalRegionProxy,
    HVDCLinkDispatchViewProxy,
    HVDCLinkPowerFlowViewProxy,
    HVDCLinkProxy,
    HeatBusProxy,
    HydroGenerationUnitDispatchViewProxy,
    HydroGenerationUnitProxy,
    HydrogenBusProxy,
    InterconnectorPowerFlowViewProxy,
    InterconnectorProxy,
    NaturalResourceProxy,
    NetworkNodeDispatchResultViewProxy,
    NetworkTopologyViewProxy,
    NuclearGenerationTechnicalViewProxy,
    OperationalDispatchViewProxy,
    PowerFlowRunRecordProxy,
    PowerFlowViewProxy,
    ProfileProxy,
    ReservoirStorageUnitDispatchViewProxy,
    ReservoirStorageUnitProxy,
    ShuntPowerFlowViewProxy,
    ShuntUnitProxy,
    SinglePortTopologyViewProxy,
    SolarGenerationTechnicalViewProxy,
    SpatialViewProxy,
    StorageDispatchViewProxy,
    StorageTypeProxy,
    StorageUnitDispatchResultViewProxy,
    StorageUnitProxy,
    ThermalGenerationTechnicalViewProxy,
    TimestampSeriesProxy,
    TransformerPowerFlowViewProxy,
    TransformerProxy,
    TransmissionElementDispatchResultViewProxy,
    TransmissionElementPowerFlowResultViewProxy,
    TransmissionLinePowerFlowViewProxy,
    TransmissionLineProxy,
    TransmissionTypeProxy,
    TwoPortTopologyViewProxy,
    WaterBusProxy,
    WindGenerationTechnicalViewProxy,
)

_T = TypeVar("_T", bound=AssetProxy)

class CesdmModel:
    classes: Dict[str, EntityClass]
    entities: Dict[str, Dict[str, Entity]]
    inheritance: Dict[str, Union[str, List[str], None]]
    schema_manifest: SchemaManifest
    def add(self, cls_name: str | None = ..., id: Any = ..., *values: Any, **kwargs: Any) -> Any: ...
    def add_asset_lifecycle_view(self, entity_id: str, *, representsAsset: EnergyAssetInstanceProxy | str, commissioning_year: Any | None = ..., commission_date: Any | None = ..., retrofit_date: Any | None = ..., retirement_date: Any | None = ...) -> AssetLifecycleViewProxy: ...
    def add_asset_location_view(self, entity_id: str, *, representsAsset: EnergyAssetInstanceProxy | str, latitude: Any | None = ..., longitude: Any | None = ..., elevation: Any | None = ..., locatedIn: GeographicalRegionProxy | str | None = ...) -> AssetLocationViewProxy: ...
    def add_asset_planning_view(self, entity_id: str, *, representsAsset: EnergyAssetInstanceProxy | str) -> AssetPlanningViewProxy: ...
    def add_attribute(self, entity_id: str, attribute_id: str, value: Any, unit: str | None = ..., provenance_ref: str | None = ...) -> Any: ...
    def add_bus(self, bus_id: str, *, nominal_voltage: float | None = ..., region_id: str | None = ..., carrier_domain_id: str | None = ..., powerflow_bus_type: str | None = ..., voltage_magnitude_setpoint: float | None = ..., voltage_angle_setpoint: float | None = ..., latitude: float | None = ..., longitude: float | None = ...) -> ElectricalBusProxy: ...
    def add_bus_location_view(self, entity_id: str, *, representsAsset: NetworkNodeProxy | str, latitude: Any | None = ..., longitude: Any | None = ..., elevation: Any | None = ..., locatedIn: GeographicalRegionProxy | str | None = ...) -> BusLocationViewProxy: ...
    def add_carrier_domain(self, entity_id: str, *, hasCarrier: EnergyCarrierProxy | EnergyCarrierId, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ...) -> CarrierDomainProxy: ...
    def add_controller_view_avr_ac1_a(self, entity_id: str, *, representsAsset: GenerationUnitProxy | str, AVR_Tr: Any | None = ..., AVR_AC1A_Ka: Any | None = ..., AVR_AC1A_Ta: Any | None = ..., AVR_AC1A_Tb: Any | None = ..., AVR_AC1A_Tc: Any | None = ..., AVR_AC1A_Ke: Any | None = ..., AVR_AC1A_Te: Any | None = ..., AVR_AC1A_Kf: Any | None = ..., AVR_AC1A_Tf: Any | None = ..., AVR_AC1A_Kc: Any | None = ..., AVR_AC1A_Kd: Any | None = ..., AVR_Va_min: Any | None = ..., AVR_Va_max: Any | None = ..., AVR_Efd_min: Any | None = ..., AVR_Efd_max: Any | None = ...) -> ControllerViewAVRAC1AProxy: ...
    def add_controller_view_avr_ieeet1(self, entity_id: str, *, representsAsset: GenerationUnitProxy | str, AVR_Tr: Any | None = ..., AVR_IEEET1_Ka: Any | None = ..., AVR_IEEET1_Ta: Any | None = ..., AVR_IEEET1_Ke: Any | None = ..., AVR_IEEET1_Te: Any | None = ..., AVR_IEEET1_Kf: Any | None = ..., AVR_IEEET1_Tf: Any | None = ..., AVR_Vr_min: Any | None = ..., AVR_Vr_max: Any | None = ..., AVR_Efd_min: Any | None = ..., AVR_Efd_max: Any | None = ...) -> ControllerViewAVRIEEET1Proxy: ...
    def add_controller_view_avr_sexs(self, entity_id: str, *, representsAsset: GenerationUnitProxy | str, AVR_SEXS_Ka: Any | None = ..., AVR_SEXS_Ta: Any | None = ..., AVR_Efd_min: Any | None = ..., AVR_Efd_max: Any | None = ...) -> ControllerViewAVRSEXSProxy: ...
    def add_controller_view_avr_st1_a(self, entity_id: str, *, representsAsset: GenerationUnitProxy | str, AVR_Tr: Any | None = ..., AVR_ST1A_Ka: Any | None = ..., AVR_ST1A_Ta: Any | None = ..., AVR_ST1A_Tb: Any | None = ..., AVR_ST1A_Tc: Any | None = ..., AVR_ST1A_Kl: Any | None = ..., AVR_Va_min: Any | None = ..., AVR_Va_max: Any | None = ..., AVR_Efd_min: Any | None = ..., AVR_Efd_max: Any | None = ...) -> ControllerViewAVRST1AProxy: ...
    def add_controller_view_gov_ggov1(self, entity_id: str, *, GOV_Pmax: Any, representsAsset: GenerationUnitProxy | str, GOV_GGOV1_R: Any | None = ..., GOV_GGOV1_Tpelec: Any | None = ..., GOV_GGOV1_Kpgov: Any | None = ..., GOV_GGOV1_Kigov: Any | None = ..., GOV_GGOV1_Kdgov: Any | None = ..., GOV_GGOV1_Tdgov: Any | None = ..., GOV_GGOV1_Tact: Any | None = ..., GOV_GGOV1_T3: Any | None = ..., GOV_GGOV1_Ropen: Any | None = ..., GOV_GGOV1_Rclose: Any | None = ..., GOV_GGOV1_Kimw: Any | None = ..., GOV_GGOV1_Aset: Any | None = ..., GOV_GGOV1_Ka: Any | None = ..., GOV_GGOV1_Ta: Any | None = ..., GOV_Db: Any | None = ..., GOV_Pmin: Any | None = ...) -> ControllerViewGOVGGOV1Proxy: ...
    def add_controller_view_gov_hygov(self, entity_id: str, *, GOV_Pmax: Any, representsAsset: GenerationUnitProxy | str, GOV_HYGOV_R: Any | None = ..., GOV_HYGOV_r: Any | None = ..., GOV_HYGOV_Tr: Any | None = ..., GOV_HYGOV_Tf: Any | None = ..., GOV_HYGOV_Tg: Any | None = ..., GOV_HYGOV_Tw: Any | None = ..., GOV_HYGOV_At: Any | None = ..., GOV_HYGOV_Dturb: Any | None = ..., GOV_HYGOV_qNL: Any | None = ..., GOV_Pmin: Any | None = ...) -> ControllerViewGOVHYGOVProxy: ...
    def add_controller_view_gov_ieeeg1(self, entity_id: str, *, GOV_Pmax: Any, representsAsset: GenerationUnitProxy | str, GOV_IEEEG1_R: Any | None = ..., GOV_IEEEG1_T1: Any | None = ..., GOV_IEEEG1_T2: Any | None = ..., GOV_IEEEG1_T3: Any | None = ..., GOV_Db: Any | None = ..., GOV_Pmin: Any | None = ...) -> ControllerViewGOVIEEEG1Proxy: ...
    def add_controller_view_pss_pss2_a(self, entity_id: str, *, representsAsset: GenerationUnitProxy | str, PSS_PSS2A_Ks1: Any | None = ..., PSS_PSS2A_Ks2: Any | None = ..., PSS_PSS2A_T6: Any | None = ..., PSS_PSS2A_T7: Any | None = ..., PSS_PSS2A_T8: Any | None = ..., PSS_PSS2A_T9: Any | None = ..., PSS_PSS2A_M: Any | None = ..., PSS_PSS2A_N: Any | None = ..., PSS_PSS2A_Tw1: Any | None = ..., PSS_PSS2A_Tw2: Any | None = ..., PSS_PSS2A_Tw3: Any | None = ..., PSS_PSS2A_T1: Any | None = ..., PSS_PSS2A_T2: Any | None = ..., PSS_PSS2A_T3: Any | None = ..., PSS_PSS2A_T4: Any | None = ..., PSS_Vs_max: Any | None = ..., PSS_Vs_min: Any | None = ...) -> ControllerViewPSSPSS2AProxy: ...
    def add_controller_view_pss_pss2_b(self, entity_id: str, *, representsAsset: GenerationUnitProxy | str, PSS_PSS2B_Ks1: Any | None = ..., PSS_PSS2B_Ks2: Any | None = ..., PSS_PSS2B_Ks3: Any | None = ..., PSS_PSS2B_T6: Any | None = ..., PSS_PSS2B_T7: Any | None = ..., PSS_PSS2B_T8: Any | None = ..., PSS_PSS2B_T9: Any | None = ..., PSS_PSS2B_M: Any | None = ..., PSS_PSS2B_N: Any | None = ..., PSS_PSS2B_Tw1: Any | None = ..., PSS_PSS2B_Tw2: Any | None = ..., PSS_PSS2B_Tw3: Any | None = ..., PSS_PSS2B_Tw4: Any | None = ..., PSS_PSS2B_T1: Any | None = ..., PSS_PSS2B_T2: Any | None = ..., PSS_PSS2B_T3: Any | None = ..., PSS_PSS2B_T4: Any | None = ..., PSS_Vs_max: Any | None = ..., PSS_Vs_min: Any | None = ...) -> ControllerViewPSSPSS2BProxy: ...
    def add_controller_view_pss_stab1(self, entity_id: str, *, representsAsset: GenerationUnitProxy | str, PSS_STAB1_Kstab: Any | None = ..., PSS_STAB1_Tw: Any | None = ..., PSS_STAB1_T1: Any | None = ..., PSS_STAB1_T2: Any | None = ..., PSS_STAB1_T3: Any | None = ..., PSS_STAB1_T4: Any | None = ..., PSS_Vs_max: Any | None = ..., PSS_Vs_min: Any | None = ...) -> ControllerViewPSSSTAB1Proxy: ...
    def add_conversion_dispatch_view(self, entity_id: str, *, representsAsset: ConversionUnitProxy | str) -> ConversionDispatchViewProxy: ...
    def add_conversion_port(self, entity_id: str, *, port_direction: Any, flow_coefficient: Any, belongsToUnit: ConversionUnitProxy | str, atNode: NetworkNodeProxy | str, hasCarrier: EnergyCarrierProxy | EnergyCarrierId, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., is_reference_port: Any | None = ..., minimum_flow_fraction: Any | None = ..., maximum_flow_fraction: Any | None = ..., maximum_output_power: Any | None = ...) -> ConversionPortProxy: ...
    def add_conversion_unit(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., hasTechnology: EnergyTechnologyTypeProxy | str | None = ...) -> ConversionUnitProxy: ...
    def add_converter_type(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., energy_conversion_efficiency: Any | None = ..., dispatch_type: Any | None = ..., variable_operating_cost: Any | None = ..., fixed_operating_cost: Any | None = ..., investment_cost: Any | None = ..., technical_lifetime: Any | None = ..., discount_rate: Any | None = ..., salvage_fraction_value: Any | None = ..., maximum_ramp_rate_up: Any | None = ..., maximum_ramp_rate_down: Any | None = ..., minimum_up_time: Any | None = ..., minimum_down_time: Any | None = ..., hot_start_cost: Any | None = ..., cold_start_cost: Any | None = ..., ramping_cost_increase: Any | None = ..., ramping_cost_decrease: Any | None = ..., generator_technology_type: Any | None = ..., comment: Any | None = ..., net_electrical_efficiency: Any | None = ..., net_thermal_efficiency: Any | None = ..., rated_electrical_power_capacity: Any | None = ..., rated_thermal_output_capacity: Any | None = ..., economic_lifetime: Any | None = ...) -> ConverterTypeProxy: ...
    def add_demand_dispatch_view(self, entity_id: str, *, representsAsset: DemandUnitProxy | str, annual_energy_demand: Any | None = ..., maximum_energy_demand: Any | None = ..., demand_type: Any | None = ..., is_demand_flexible: Any | None = ..., flexibility_time_resolution: Any | None = ..., flexibility_window_time_start: Any | None = ..., flexibility_window_time_end: Any | None = ..., maximum_upward_adjustment: Any | None = ..., maximum_downward_adjustment: Any | None = ..., value_of_lost_load: Any | None = ..., variable_operating_cost: Any | None = ..., hasDemandProfile: ProfileProxy | str | None = ...) -> DemandDispatchViewProxy: ...
    def add_demand_power_flow_view(self, entity_id: str, *, active_power_demand: Any, representsAsset: DemandUnitProxy | str, reactive_power_demand: Any | None = ..., power_factor: Any | None = ...) -> DemandPowerFlowViewProxy: ...
    def add_demand_unit(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ...) -> DemandUnitProxy: ...
    def add_demand_unit_dispatch_result_view(self, entity_id: str, *, hasRunRecord: DispatchRunRecordProxy | str, representsAsset: DemandUnitProxy | str, total_served_energy: Any | None = ..., total_curtailed_energy: Any | None = ..., curtailment_rate: Any | None = ..., total_variable_cost: Any | None = ..., hasServedDemandProfile: ProfileProxy | str | None = ..., hasCurtailedDemandProfile: ProfileProxy | str | None = ..., hasDemandDualProfile: ProfileProxy | str | None = ...) -> DemandUnitDispatchResultViewProxy: ...
    def add_dispatch_run_record(self, entity_id: str, *, hasTimestampSeries: TimestampSeriesProxy | str, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., run_timestamp: Any | None = ..., solver_name: Any | None = ..., solver_status: Any | None = ..., objective_value: Any | None = ..., optimality_gap: Any | None = ..., solve_time_seconds: Any | None = ..., scenario_year: Any | None = ..., co2_price: Any | None = ..., hasInputRun: RunRecordProxy | str | None = ...) -> DispatchRunRecordProxy: ...
    def add_dynamic_run_record(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., run_timestamp: Any | None = ..., solver_name: Any | None = ..., solve_time_seconds: Any | None = ..., integration_method: Any | None = ..., simulation_timestep_seconds: Any | None = ..., simulation_duration_seconds: Any | None = ..., hasInputRun: RunRecordProxy | str | None = ...) -> DynamicRunRecordProxy: ...
    def add_electrical_bus(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., nominal_voltage: Any | None = ..., locatedIn: GeographicalRegionProxy | str | None = ..., belongsToCarrierDomain: CarrierDomainProxy | str | None = ...) -> ElectricalBusProxy: ...
    def add_electrical_bus_power_flow_result_view(self, entity_id: str, *, hasRunRecord: PowerFlowRunRecordProxy | str, representsAsset: ElectricalBusProxy | str, voltage_magnitude: Any | None = ..., voltage_angle: Any | None = ..., net_active_power_injection: Any | None = ..., net_reactive_power_injection: Any | None = ..., average_voltage_magnitude: Any | None = ..., min_voltage_magnitude: Any | None = ..., max_voltage_magnitude: Any | None = ..., hasVoltageMagnitudeProfile: ProfileProxy | str | None = ..., hasVoltageAngleProfile: ProfileProxy | str | None = ...) -> ElectricalBusPowerFlowResultViewProxy: ...
    def add_electrical_bus_power_flow_view(self, entity_id: str, *, representsAsset: ElectricalBusProxy | str) -> ElectricalBusPowerFlowViewProxy: ...
    def add_energy_carrier(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., co2_emission_intensity: Any | None = ..., energy_carrier_cost: Any | None = ..., carrier_group: Any | None = ..., carrier_type: Any | None = ..., is_primary_fuel: Any | None = ..., is_secondary_fuel: Any | None = ...) -> EnergyCarrierProxy: ...
    def add_energy_system_model(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., base_mva: Any | None = ..., co2_price: Any | None = ...) -> EnergySystemModelProxy: ...
    def add_energy_technology_type(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., energy_conversion_efficiency: Any | None = ..., dispatch_type: Any | None = ..., variable_operating_cost: Any | None = ..., fixed_operating_cost: Any | None = ..., investment_cost: Any | None = ..., technical_lifetime: Any | None = ..., discount_rate: Any | None = ..., salvage_fraction_value: Any | None = ..., maximum_ramp_rate_up: Any | None = ..., maximum_ramp_rate_down: Any | None = ..., minimum_up_time: Any | None = ..., minimum_down_time: Any | None = ..., hot_start_cost: Any | None = ..., cold_start_cost: Any | None = ..., ramping_cost_increase: Any | None = ..., ramping_cost_decrease: Any | None = ..., generator_technology_type: Any | None = ..., comment: Any | None = ...) -> EnergyTechnologyTypeProxy: ...
    def add_entity(self, entity_class: str, entity_id: str) -> Any: ...
    def add_external_supply(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., hasOutputCarrier: EnergyCarrierProxy | EnergyCarrierId | None = ...) -> ExternalSupplyProxy: ...
    def add_external_supply_dispatch_view(self, entity_id: str, *, supply_capacity: Any, is_slack: Any, representsAsset: ExternalSupplyProxy | str, supply_price: Any | None = ...) -> ExternalSupplyDispatchViewProxy: ...
    def add_gas_bus(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., nominal_pressure: Any | None = ..., locatedIn: GeographicalRegionProxy | str | None = ..., belongsToCarrierDomain: CarrierDomainProxy | str | None = ...) -> GasBusProxy: ...
    def add_generation_dispatch_view(self, entity_id: str, *, representsAsset: GenerationUnitProxy | str, generator_technology_type: Any | None = ..., nominal_power_capacity: Any | None = ..., minimum_generation: Any | None = ..., maximum_generation: Any | None = ..., variable_operating_cost: Any | None = ..., fixed_operating_cost: Any | None = ..., energy_conversion_efficiency: Any | None = ..., annual_resource_potential: Any | None = ..., dispatch_type: Any | None = ..., maximum_ramp_rate_up: Any | None = ..., maximum_ramp_rate_down: Any | None = ..., minimum_up_time: Any | None = ..., minimum_down_time: Any | None = ..., hot_start_cost: Any | None = ..., cold_start_cost: Any | None = ..., machine_role: Any | None = ..., turbine_efficiency: Any | None = ..., maximum_pumping_power: Any | None = ..., pumping_efficiency: Any | None = ..., hasAvailabilityProfile: ProfileProxy | str | None = ..., hasRunOfRiverInflowProfile: ProfileProxy | str | None = ...) -> GenerationDispatchViewProxy: ...
    def add_generation_unit(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., hasTechnology: GeneratorTypeProxy | GeneratorTypeId | None = ..., hasInputResource: NaturalResourceProxy | NaturalResourceId | None = ..., hasInputCarrier: EnergyCarrierProxy | EnergyCarrierId | None = ..., hasOutputCarrier: EnergyCarrierProxy | EnergyCarrierId | None = ...) -> GenerationUnitProxy: ...
    def add_generation_unit_dispatch_result_view(self, entity_id: str, *, hasRunRecord: DispatchRunRecordProxy | str, representsAsset: GenerationUnitProxy | str, total_generation: Any | None = ..., capacity_factor: Any | None = ..., full_load_hours: Any | None = ..., total_variable_cost: Any | None = ..., total_start_cost: Any | None = ..., co2_emissions: Any | None = ..., hasDispatchProfile: ProfileProxy | str | None = ..., hasCommitmentProfile: ProfileProxy | str | None = ..., hasStartupProfile: ProfileProxy | str | None = ..., hasShutdownProfile: ProfileProxy | str | None = ..., hasReducedCostProfile: ProfileProxy | str | None = ...) -> GenerationUnitDispatchResultViewProxy: ...
    def add_generation_unit_power_flow_result_view(self, entity_id: str, *, hasRunRecord: PowerFlowRunRecordProxy | str, representsAsset: GenerationUnitProxy | str, active_power_output: Any | None = ..., reactive_power_output: Any | None = ..., hasActivePowerOutputProfile: ProfileProxy | str | None = ..., hasReactivePowerOutputProfile: ProfileProxy | str | None = ...) -> GenerationUnitPowerFlowResultViewProxy: ...
    def add_generator(self, id: str, *, technology: str, bus: str | None = ..., nominal_power_capacity: float | None = ..., **kwargs: Any) -> GenerationUnitProxy: ...
    def add_generator_dynamic_result_view(self, entity_id: str, *, hasRunRecord: DynamicRunRecordProxy | str, representsAsset: GenerationUnitProxy | str, max_rotor_angle_deviation: Any | None = ..., max_speed_deviation: Any | None = ..., settling_time_seconds: Any | None = ..., remained_stable: Any | None = ..., hasRotorAngleProfile: ProfileProxy | str | None = ..., hasSpeedDeviationProfile: ProfileProxy | str | None = ...) -> GeneratorDynamicResultViewProxy: ...
    def add_generator_dynamic_view_subtransient(self, entity_id: str, *, MACHINE_rated_mva: Any, MACHINE_rated_kv: Any, MACHINE_model: Any, representsAsset: GenerationUnitProxy | str, MACHINE_H: Any | None = ..., MACHINE_D: Any | None = ..., MACHINE_xd: Any | None = ..., MACHINE_xq: Any | None = ..., MACHINE_xd_prime: Any | None = ..., MACHINE_xq_prime: Any | None = ..., MACHINE_Td0_prime: Any | None = ..., MACHINE_Tq0_prime: Any | None = ..., MACHINE_xd_dprime: Any | None = ..., MACHINE_xq_dprime: Any | None = ..., MACHINE_Td0_dprime: Any | None = ..., MACHINE_Tq0_dprime: Any | None = ..., MACHINE_ra: Any | None = ..., MACHINE_xl: Any | None = ..., hasAutomaticVoltageRegulator: ControllerViewAVRProxy | str | None = ..., hasTurbineGovernor: ControllerViewGOVProxy | str | None = ..., hasPowerSystemStabilizer: ControllerViewPSSProxy | str | None = ...) -> GeneratorDynamicViewSubtransientProxy: ...
    def add_generator_power_flow_view(self, entity_id: str, *, powerflow_bus_type: Any, active_power_setpoint: Any, representsAsset: GenerationUnitProxy | str, voltage_magnitude_setpoint: Any | None = ..., voltage_angle_setpoint: Any | None = ..., reactive_power_setpoint: Any | None = ..., maximum_active_power_output: Any | None = ..., minimum_active_power_output: Any | None = ..., maximum_reactive_power_output: Any | None = ..., minimum_reactive_power_output: Any | None = ...) -> GeneratorPowerFlowViewProxy: ...
    def add_generator_type(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., energy_conversion_efficiency: Any | None = ..., dispatch_type: Any | None = ..., variable_operating_cost: Any | None = ..., fixed_operating_cost: Any | None = ..., investment_cost: Any | None = ..., technical_lifetime: Any | None = ..., discount_rate: Any | None = ..., salvage_fraction_value: Any | None = ..., maximum_ramp_rate_up: Any | None = ..., maximum_ramp_rate_down: Any | None = ..., minimum_up_time: Any | None = ..., minimum_down_time: Any | None = ..., hot_start_cost: Any | None = ..., cold_start_cost: Any | None = ..., ramping_cost_increase: Any | None = ..., ramping_cost_decrease: Any | None = ..., generator_technology_type: Any | None = ..., comment: Any | None = ..., economic_lifetime: Any | None = ..., co2_emission_factor: Any | None = ..., fuel_consumption_rate: Any | None = ..., hasInputCarrier: EnergyCarrierProxy | EnergyCarrierId | None = ..., hasInputResource: NaturalResourceProxy | NaturalResourceId | None = ..., hasOutputCarrier: EnergyCarrierProxy | EnergyCarrierId | None = ...) -> GeneratorTypeProxy: ...
    def add_geographical_region(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., isSubRegionOf: GeographicalRegionProxy | str | None = ...) -> GeographicalRegionProxy: ...
    def add_heat_bus(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., nominal_temperature: Any | None = ..., nominal_pressure: Any | None = ..., locatedIn: GeographicalRegionProxy | str | None = ..., belongsToCarrierDomain: CarrierDomainProxy | str | None = ...) -> HeatBusProxy: ...
    def add_hvdc_link(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., converter_technology: Any | None = ...) -> HVDCLinkProxy: ...
    def add_hvdc_link_dispatch_view(self, entity_id: str, *, max_flow: Any, representsAsset: HVDCLinkProxy | str, variable_operating_cost: Any | None = ...) -> HVDCLinkDispatchViewProxy: ...
    def add_hvdc_link_power_flow_view(self, entity_id: str, *, hvdc_technology_type: Any, p_max_hvdc: Any, representsAsset: HVDCLinkProxy | str, dc_voltage_kv: Any | None = ..., active_power_setpoint_from_to: Any | None = ..., p_min_hvdc: Any | None = ..., converter_loss_coefficient: Any | None = ..., converter_rating_from: Any | None = ..., converter_rating_to: Any | None = ...) -> HVDCLinkPowerFlowViewProxy: ...
    def add_hydro_generation_unit(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., hydraulic_head: Any | None = ..., turbine_type: Any | None = ..., is_reversible: Any | None = ..., hasTechnology: GeneratorTypeProxy | GeneratorTypeId | None = ..., hasInputResource: NaturalResourceProxy | NaturalResourceId | None = ..., hasInputCarrier: EnergyCarrierProxy | EnergyCarrierId | None = ..., hasOutputCarrier: EnergyCarrierProxy | EnergyCarrierId | None = ..., drawsFromReservoir: ReservoirStorageUnitProxy | str | None = ..., dischargesToReservoir: ReservoirStorageUnitProxy | str | None = ...) -> HydroGenerationUnitProxy: ...
    def add_hydro_generation_unit_dispatch_view(self, entity_id: str, *, representsAsset: HydroGenerationUnitProxy | str, nominal_power_capacity: Any | None = ..., minimum_generation: Any | None = ..., maximum_generation: Any | None = ..., variable_operating_cost: Any | None = ..., annual_resource_potential: Any | None = ..., dispatch_type: Any | None = ..., machine_role: Any | None = ..., turbine_efficiency: Any | None = ..., maximum_pumping_power: Any | None = ..., pumping_efficiency: Any | None = ..., maximum_ramp_rate_up: Any | None = ..., maximum_ramp_rate_down: Any | None = ..., hasRunOfRiverInflowProfile: ProfileProxy | str | None = ...) -> HydroGenerationUnitDispatchViewProxy: ...
    def add_hydro_generator(self, asset_id: str, *, bus_id: str, nominal_power_capacity: float, technology_id: str = ..., machine_role: str | None = ..., draws_from_reservoir: str | None = ..., discharges_to_reservoir: str | None = ..., **attrs: Any) -> HydroGenerationUnitProxy: ...
    def add_hydrogen_bus(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., nominal_pressure: Any | None = ..., locatedIn: GeographicalRegionProxy | str | None = ..., belongsToCarrierDomain: CarrierDomainProxy | str | None = ...) -> HydrogenBusProxy: ...
    def add_interconnector(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ...) -> InterconnectorProxy: ...
    def add_interconnector_power_flow_view(self, entity_id: str, *, representsAsset: InterconnectorProxy | str, maximum_power_flow_from_to: Any | None = ..., maximum_power_flow_to_from: Any | None = ...) -> InterconnectorPowerFlowViewProxy: ...
    def add_natural_resource(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., resource_group: Any | None = ..., resource_type: Any | None = ..., natural_resource_unit: Any | None = ...) -> NaturalResourceProxy: ...
    def add_network_node_dispatch_result_view(self, entity_id: str, *, hasRunRecord: DispatchRunRecordProxy | str, representsAsset: NetworkNodeProxy | str, average_nodal_price: Any | None = ..., min_nodal_price: Any | None = ..., max_nodal_price: Any | None = ..., hasNodalPriceProfile: ProfileProxy | str | None = ...) -> NetworkNodeDispatchResultViewProxy: ...
    def add_network_topology_view(self, entity_id: str, *, representsAsset: EnergyAssetInstanceProxy | str) -> NetworkTopologyViewProxy: ...
    def add_nuclear_generation_technical_view(self, entity_id: str, *, representsAsset: EnergyAssetInstanceProxy | str, reactor_type: Any | None = ..., thermal_capacity: Any | None = ...) -> NuclearGenerationTechnicalViewProxy: ...
    def add_nuclear_generator(self, asset_id: str, *, bus_id: str, nominal_power_capacity: float, technology_id: str = ..., **attrs: Any) -> GenerationUnitProxy: ...
    def add_operational_dispatch_view(self, entity_id: str) -> OperationalDispatchViewProxy: ...
    def add_phs_closed_loop(self, hydro_id: str, upper_reservoir_id: str, *, lower_reservoir_id: str | None = ..., bus_id: str | None = ..., nominal_power_capacity: float | None = ..., maximum_pumping_power: float | None = ..., pumping_efficiency: float | None = ..., turbine_efficiency: float | None = ..., **attrs: Any) -> tuple[ReservoirStorageUnitProxy, HydroGenerationUnitProxy]: ...
    def add_phs_open_loop(self, hydro_id: str, upper_reservoir_id: str, *, lower_reservoir_id: str | None = ..., bus_id: str | None = ..., nominal_power_capacity: float | None = ..., maximum_pumping_power: float | None = ..., pumping_efficiency: float | None = ..., turbine_efficiency: float | None = ..., **attrs: Any) -> tuple[ReservoirStorageUnitProxy, HydroGenerationUnitProxy]: ...
    def add_power_flow_run_record(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., run_timestamp: Any | None = ..., solver_name: Any | None = ..., solve_time_seconds: Any | None = ..., converged: Any | None = ..., iteration_count: Any | None = ..., convergence_tolerance: Any | None = ..., hasInputRun: RunRecordProxy | str | None = ..., hasTimestampSeries: TimestampSeriesProxy | str | None = ...) -> PowerFlowRunRecordProxy: ...
    def add_power_flow_view(self, entity_id: str) -> PowerFlowViewProxy: ...
    def add_profile(self, entity_id: str, *, profile_type: Any, data_reference: Any, hasTimestampSeries: TimestampSeriesProxy | str, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., profile_unit: Any | None = ...) -> ProfileProxy: ...
    def add_relation(self, entity_id: str, relation_id: str, target_entity_id: str, **kwargs: Any) -> Any: ...
    def add_relation_if_allowed(self, entity_id: str, relation_id: str, target_id: str, *, strict: bool = ...) -> Any: ...
    def add_reservoir_hydro(self, hydro_id: str, reservoir_id: str, *, bus_id: str | None = ..., nominal_power_capacity: float | None = ..., energy_storage_capacity: float | None = ..., technology_id: str = ..., **attrs: Any) -> tuple[ReservoirStorageUnitProxy, HydroGenerationUnitProxy]: ...
    def add_reservoir_storage(self, reservoir_id: str, *, technology_id: str | None = ..., energy_storage_capacity: float | None = ..., annual_natural_inflow_energy: float | None = ..., **attrs: Any) -> ReservoirStorageUnitProxy: ...
    def add_reservoir_storage_unit(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., storesCarrier: EnergyCarrierProxy | EnergyCarrierId | None = ..., storesResource: NaturalResourceProxy | NaturalResourceId | None = ..., hasTechnology: StorageTypeProxy | StorageTypeId | None = ..., suppliesResourceTo: HydroGenerationUnitProxy | str | None = ...) -> ReservoirStorageUnitProxy: ...
    def add_reservoir_storage_unit_dispatch_view(self, entity_id: str, *, representsAsset: ReservoirStorageUnitProxy | str, energy_storage_capacity: Any | None = ..., annual_natural_inflow_energy: Any | None = ..., minimum_state_of_charge: Any | None = ..., maximum_state_of_charge: Any | None = ..., initial_state_of_charge: Any | None = ..., self_discharge_rate: Any | None = ..., storage_technology_type: Any | None = ..., hasNaturalInflowProfile: ProfileProxy | str | None = ...) -> ReservoirStorageUnitDispatchViewProxy: ...
    def add_run_of_river(self, asset_id: str, *, bus_id: str | None = ..., nominal_power_capacity: float | None = ..., technology_id: str = ..., **attrs: Any) -> HydroGenerationUnitProxy: ...
    def add_shunt_power_flow_view(self, entity_id: str, *, representsAsset: ShuntUnitProxy | str, active_power_injection: Any | None = ..., reactive_power_injection: Any | None = ...) -> ShuntPowerFlowViewProxy: ...
    def add_shunt_unit(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ...) -> ShuntUnitProxy: ...
    def add_single_port_topology_view(self, entity_id: str, *, representsAsset: EnergyAssetInstanceProxy | str, atNode: NetworkNodeProxy | str) -> SinglePortTopologyViewProxy: ...
    def add_solar_generation_technical_view(self, entity_id: str, *, representsAsset: EnergyAssetInstanceProxy | str, tilt_angle: Any | None = ..., azimuth_angle: Any | None = ..., tracking_type: Any | None = ..., panel_technology: Any | None = ...) -> SolarGenerationTechnicalViewProxy: ...
    def add_solar_generator(self, asset_id: str, *, bus_id: str | None = ..., nominal_power_capacity: float | None = ..., technology_id: str = ..., resource_id: str = ..., **attrs: Any) -> GenerationUnitProxy: ...
    def add_spatial_view(self, entity_id: str, *, representsAsset: EnergyAssetInstanceProxy | str) -> SpatialViewProxy: ...
    def add_storage_dispatch_view(self, entity_id: str, *, representsAsset: StorageUnitProxy | str, nominal_power_capacity: Any | None = ..., energy_storage_capacity: Any | None = ..., annual_natural_inflow_energy: Any | None = ..., charging_efficiency: Any | None = ..., discharging_efficiency: Any | None = ..., self_discharge_rate: Any | None = ..., minimum_state_of_charge: Any | None = ..., maximum_state_of_charge: Any | None = ..., initial_state_of_charge: Any | None = ..., maximum_ramp_rate_up: Any | None = ..., maximum_ramp_rate_down: Any | None = ..., variable_operating_cost: Any | None = ..., charging_variable_operating_cost: Any | None = ..., maximum_charging_power: Any | None = ..., maximum_discharging_power: Any | None = ..., storage_technology_type: Any | None = ...) -> StorageDispatchViewProxy: ...
    def add_storage_type(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., energy_conversion_efficiency: Any | None = ..., dispatch_type: Any | None = ..., variable_operating_cost: Any | None = ..., fixed_operating_cost: Any | None = ..., investment_cost: Any | None = ..., technical_lifetime: Any | None = ..., discount_rate: Any | None = ..., salvage_fraction_value: Any | None = ..., maximum_ramp_rate_up: Any | None = ..., maximum_ramp_rate_down: Any | None = ..., minimum_up_time: Any | None = ..., minimum_down_time: Any | None = ..., hot_start_cost: Any | None = ..., cold_start_cost: Any | None = ..., ramping_cost_increase: Any | None = ..., ramping_cost_decrease: Any | None = ..., generator_technology_type: Any | None = ..., comment: Any | None = ..., energy_storage_capacity: Any | None = ..., nominal_power_capacity: Any | None = ..., charging_efficiency: Any | None = ..., discharging_efficiency: Any | None = ..., self_discharge_rate: Any | None = ..., minimum_state_of_charge: Any | None = ..., maximum_state_of_charge: Any | None = ..., maximum_required_units: Any | None = ..., minimum_required_units: Any | None = ..., unit_nominal_size: Any | None = ..., has_natural_inflow: Any | None = ..., has_active_charging: Any | None = ..., economic_lifetime: Any | None = ..., storage_technology_type: Any | None = ..., hasCarrier: EnergyCarrierProxy | EnergyCarrierId | None = ..., storesResource: NaturalResourceProxy | NaturalResourceId | None = ...) -> StorageTypeProxy: ...
    def add_storage_unit(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., storesCarrier: EnergyCarrierProxy | EnergyCarrierId | None = ..., storesResource: NaturalResourceProxy | NaturalResourceId | None = ..., hasTechnology: EnergyTechnologyTypeProxy | str | GeneratorTypeProxy | GeneratorTypeId | StorageTypeProxy | StorageTypeId | ConverterTypeProxy | TransmissionTypeProxy | None = ...) -> StorageUnitProxy: ...
    def add_storage_unit_dispatch_result_view(self, entity_id: str, *, hasRunRecord: DispatchRunRecordProxy | str, representsAsset: StorageUnitProxy | str, total_discharge_energy: Any | None = ..., total_charge_energy: Any | None = ..., storage_cycles: Any | None = ..., average_round_trip_efficiency: Any | None = ..., hasDischargeProfile: ProfileProxy | str | None = ..., hasChargeProfile: ProfileProxy | str | None = ..., hasStateOfChargeProfile: ProfileProxy | str | None = ..., hasDischargeDualProfile: ProfileProxy | str | None = ..., hasChargeDualProfile: ProfileProxy | str | None = ...) -> StorageUnitDispatchResultViewProxy: ...
    def add_thermal_generation_technical_view(self, entity_id: str, *, representsAsset: EnergyAssetInstanceProxy | str, cooling_type: Any | None = ...) -> ThermalGenerationTechnicalViewProxy: ...
    def add_thermal_generator(self, asset_id: str, *, bus_id: str | None = ..., nominal_power_capacity: float | None = ..., technology_id: str = ..., fuel_carrier_id: str | None = ..., **attrs: Any) -> GenerationUnitProxy: ...
    def add_timestamp_series(self, entity_id: str, *, start_datetime: Any, resolution: Any, length: Any, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., timezone: Any | None = ...) -> TimestampSeriesProxy: ...
    def add_transformer(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ...) -> TransformerProxy: ...
    def add_transformer_power_flow_view(self, entity_id: str, *, representsAsset: TransformerProxy | str, rated_primary_voltage: Any | None = ..., rated_secondary_voltage: Any | None = ..., short_circuit_voltage_in_percentage: Any | None = ..., thermal_capacity_rating: Any | None = ..., tap_ratio: Any | None = ..., phase_shift_angle: Any | None = ...) -> TransformerPowerFlowViewProxy: ...
    def add_transmission_element_dispatch_result_view(self, entity_id: str, *, hasRunRecord: DispatchRunRecordProxy | str, representsAsset: InterconnectorProxy | str | TransmissionLineProxy, total_flow_1_to_2: Any | None = ..., total_flow_2_to_1: Any | None = ..., congestion_hours: Any | None = ..., total_congestion_rent: Any | None = ..., hasFlowProfile: ProfileProxy | str | None = ..., hasShadowPriceProfile: ProfileProxy | str | None = ...) -> TransmissionElementDispatchResultViewProxy: ...
    def add_transmission_element_power_flow_result_view(self, entity_id: str, *, hasRunRecord: PowerFlowRunRecordProxy | str, representsAsset: TransmissionLineProxy | str | TransformerProxy | InterconnectorProxy, active_power_flow_from: Any | None = ..., reactive_power_flow_from: Any | None = ..., active_power_flow_to: Any | None = ..., reactive_power_flow_to: Any | None = ..., active_power_loss: Any | None = ..., reactive_power_loss: Any | None = ..., current_magnitude: Any | None = ..., loading_percent: Any | None = ..., average_loading_percent: Any | None = ..., max_loading_percent: Any | None = ..., total_active_power_loss: Any | None = ..., hasLoadingProfile: ProfileProxy | str | None = ..., hasActivePowerLossProfile: ProfileProxy | str | None = ...) -> TransmissionElementPowerFlowResultViewProxy: ...
    def add_transmission_line(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ...) -> TransmissionLineProxy: ...
    def add_transmission_line_power_flow_view(self, entity_id: str, *, representsAsset: TransmissionLineProxy | str, series_resistance_per_km: Any | None = ..., series_reactance_per_km: Any | None = ..., shunt_susceptance_per_km: Any | None = ..., line_length: Any | None = ..., parallel_circuit_count: Any | None = ..., thermal_capacity_rating: Any | None = ...) -> TransmissionLinePowerFlowViewProxy: ...
    def add_transmission_type(self, entity_id: str, *, hasCarrier: EnergyCarrierProxy | EnergyCarrierId, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., energy_conversion_efficiency: Any | None = ..., dispatch_type: Any | None = ..., variable_operating_cost: Any | None = ..., fixed_operating_cost: Any | None = ..., investment_cost: Any | None = ..., technical_lifetime: Any | None = ..., discount_rate: Any | None = ..., salvage_fraction_value: Any | None = ..., maximum_ramp_rate_up: Any | None = ..., maximum_ramp_rate_down: Any | None = ..., minimum_up_time: Any | None = ..., minimum_down_time: Any | None = ..., hot_start_cost: Any | None = ..., cold_start_cost: Any | None = ..., ramping_cost_increase: Any | None = ..., ramping_cost_decrease: Any | None = ..., generator_technology_type: Any | None = ..., comment: Any | None = ..., line_length: Any | None = ..., series_resistance_per_km: Any | None = ..., series_reactance_per_km: Any | None = ..., shunt_susceptance_per_km: Any | None = ..., thermal_capacity_rating: Any | None = ..., parallel_circuit_count: Any | None = ...) -> TransmissionTypeProxy: ...
    def add_two_port_topology_view(self, entity_id: str, *, representsAsset: TransmissionElementProxy | str, fromNode: NetworkNodeProxy | str, toNode: NetworkNodeProxy | str, from_switch_closed: Any | None = ..., to_switch_closed: Any | None = ...) -> TwoPortTopologyViewProxy: ...
    def add_water_bus(self, entity_id: str, *, name: Any | None = ..., long_name: Any | None = ..., description: Any | None = ..., nominal_head: Any | None = ..., locatedIn: GeographicalRegionProxy | str | None = ..., belongsToCarrierDomain: CarrierDomainProxy | str | None = ...) -> WaterBusProxy: ...
    def add_wind_generation_technical_view(self, entity_id: str, *, representsAsset: EnergyAssetInstanceProxy | str, hub_height: Any | None = ..., rotor_diameter: Any | None = ..., installation_type: Any | None = ..., number_of_turbines: Any | None = ...) -> WindGenerationTechnicalViewProxy: ...
    def add_wind_generator(self, asset_id: str, *, bus_id: str | None = ..., nominal_power_capacity: float | None = ..., technology_id: str = ..., resource_id: str = ..., **attrs: Any) -> GenerationUnitProxy: ...
    def asset(self, entity_id: str) -> AssetProxy: ...
    def asset_as(self, entity_id: str, cls: type[_T] | tuple[type[_T], ...]) -> _T: ...
    def attach_availability_profile(self, asset_or_view_id: str, profile_id: str, **kwargs: Any) -> ProfileProxy: ...
    def attach_demand_profile(self, asset_or_view_id: str, profile_id: str, **kwargs: Any) -> ProfileProxy: ...
    def attach_natural_inflow_profile(self, asset_or_view_id: str, profile_id: str, **kwargs: Any) -> ProfileProxy: ...
    def attach_profile(self, view_or_asset_id: str, relation_id: str, profile_id: str, *, timestamp_series_id: str | None = ..., create: bool = ..., profile_type: str = ..., profile_unit: str | None = ..., data_reference: str | None = ...) -> ProfileProxy: ...
    def attach_run_of_river_profile(self, asset_or_view_id: str, profile_id: str, **kwargs: Any) -> ProfileProxy: ...
    def available_add_methods(self) -> dict[str, str]: ...
    def build_class_indexes(self) -> Any: ...
    def build_inheritance_map(self, schema_dir: str | Path) -> Dict[str, List[str]]: ...
    def build_pydantic_models(self) -> Any: ...
    def class_attributes(self, class_name: str) -> List[str]: ...
    def class_defs(self) -> Any: ...
    def class_relations(self, class_name: str) -> List[str]: ...
    def connect_single_port(self, asset_id: str, node_id: str, *, view_id: str | None = ...) -> str: ...
    def connect_two_port(self, asset_id: str, from_node_id: str, to_node_id: str, *, view_id: str | None = ...) -> str: ...
    def create_demand_unit(self, asset_id: str, *, bus_id: str | None = ..., annual_energy_demand: float | None = ..., carrier_id: str | None = ..., **attrs: Any) -> DemandUnitProxy: ...
    def create_generation_unit(self, asset_id: str, *, class_name: str = ..., technology_id: str | None = ..., technology_class: str = ..., bus_id: str | None = ..., nominal_power_capacity: float | None = ..., output_carrier_id: str | None = ..., input_carrier_id: str | None = ..., input_resource_id: str | None = ..., dispatch_view_class: str | None = ..., **dispatch_attrs: Any) -> GenerationUnitProxy: ...
    def create_generation_unit_from_technology(self, asset_id: str, *, carrier: str | None = ..., technology: str | None = ..., bus_id: str | None = ..., nominal_power_capacity: float | None = ..., output_carrier_id: str | None = ..., input_carrier_id: str | None = ..., input_resource_id: str | None = ..., technology_id: str | None = ..., **dispatch_attrs: Any) -> GenerationUnitProxy: ...
    def create_hvdc_link(self, link_id: str, from_bus: str, to_bus: str, *, hvdc_technology_type: str = ..., **attrs: Any) -> HVDCLinkProxy: ...
    def create_profile(self, profile_id: str, *, timestamp_series_id: str, profile_type: str = ..., profile_unit: str | None = ..., data_reference: str | None = ...) -> ProfileProxy: ...
    def create_storage_unit(self, asset_id: str, *, bus_id: str | None = ..., technology_id: str | None = ..., energy_storage_capacity: float | None = ..., nominal_power_capacity: float | None = ..., carrier_id: str | None = ..., **attrs: Any) -> StorageUnitProxy: ...
    def create_timestamp_series(self, series_id: str, *, start_datetime: str, resolution: str, length: int, timezone: str | None = ...) -> TimestampSeriesProxy: ...
    def create_transmission_line(self, line_id: str, from_bus: str, to_bus: str, **pf_attrs: Any) -> TransmissionLineProxy: ...
    def debug_schema(self) -> Any: ...
    def dispatch_view_class_for_asset(self, asset_class: str) -> str: ...
    def ensure_carrier(self, carrier_id: str, *, name: str | None = ..., carrier_type: str | None = ..., carrier_group: str | None = ...) -> EnergyCarrierProxy: ...
    def ensure_default_library_entity(self, entity_id: str, expected_class: str | None = ...) -> bool: ...
    def ensure_dispatch_view(self, asset_id: str, view_class: str | None = ..., **attributes: Any) -> str: ...
    def ensure_entity(self, class_name: str, entity_id: str, **attributes: Any) -> AssetProxy: ...
    def ensure_resource(self, resource_id: str, *, name: str | None = ..., resource_type: str | None = ..., resource_group: str | None = ..., unit: str | None = ...) -> NaturalResourceProxy: ...
    def ensure_technology(self, technology_id: str, *, class_name: str = ..., name: str | None = ..., **attributes: Any) -> GeneratorTypeProxy: ...
    def ensure_view(self, asset_id: str, view_class: str, view_id: str | None = ..., **attributes: Any) -> str: ...
    def entity_class(self, entity_id: str) -> Optional[str]: ...
    def entity_data(self, entity_id: str) -> Dict[str, Any]: ...
    def export_csv_by_class(self, dir_path: Union[str, pathlib.Path], include_placeholders: bool = ...) -> Any: ...
    def export_csv_by_class_wide(self, dir_path: Union[str, pathlib.Path], include_placeholders: bool = ..., include_ref_meta: bool = ...) -> Any: ...
    def export_csv_by_class_wide_meta(self, dir_path: str, include_placeholders: bool = ...) -> Any: ...
    def export_csv_by_class_wide_with_schema(self, dir_path: Union[str, pathlib.Path], include_placeholders: bool = ...) -> Any: ...
    def export_csv_by_class_with_schema(self, dir_path: Union[str, pathlib.Path], include_placeholders: bool = ...) -> Any: ...
    def export_csv_hierarchical(self, dir_path: Union[str, pathlib.Path], *, wide: bool = ..., long: bool = ...) -> None: ...
    def export_datapackage(self, dir_path: Any) -> Any: ...
    def export_excel(self, path: Union[str, pathlib.Path], *, include_non_assets: bool = ...) -> None: ...
    def export_excel_flat(self, path: Union[str, pathlib.Path], *, include_non_assets: bool = ...) -> None: ...
    def export_frictionless(self, dir_path: Union[str, pathlib.Path], *, name: str = ..., title: Optional[str] = ..., description: str = ..., version: str = ..., contributors: Optional[list] = ...) -> pathlib.Path: ...
    def export_hdf5(self, path: Union[str, pathlib.Path], *, values_map: Optional[Dict[str, 'np.ndarray']] = ...) -> None: ...
    def export_json(self, path: str | pathlib.Path) -> Any: ...
    def export_json_schema(self, path: Union[str, pathlib.Path]) -> Any: ...
    def export_long_csv(self, path: str | pathlib.Path) -> Any: ...
    def export_long_csv_with_schema(self, path: Union[str, pathlib.Path]) -> Any: ...
    def export_parquet(self, path: Union[str, pathlib.Path], *, values_map: Optional[Dict[str, 'np.ndarray']] = ..., wide: bool = ...) -> None: ...
    def export_rdf_schema(self, path: Union[str, pathlib.Path], namespace: Optional[str] = ...) -> None: ...
    def export_yaml(self, path: str | pathlib.Path) -> Any: ...
    def export_yaml_hierarchical(self, path: str | pathlib.Path) -> None: ...
    def export_yaml_model(self, path: str | pathlib.Path) -> None: ...
    def field_allowed(self, entity_or_class: str, field_id: str) -> bool: ...
    def format_attribute_tree(self, groups: Dict[str, List]) -> Any: ...
    def format_class_tree(self) -> str: ...
    def generation_asset_class_from_technology(self, carrier: str | None = ..., technology: str | None = ...) -> str: ...
    def get_attr_value(self, entity_class: str, entity_id: str, attribute_id: str, default: Any = ...) -> Any: ...
    def get_attribute_value(self, entity_id: str, attribute_id: str, default: Any = ...) -> Any: ...
    def get_attributes_grouped(self, class_name: str) -> Dict[str, List[AttributeDef]]: ...
    def get_dispatch_view(self, asset_id: str) -> str | None: ...
    def get_effective_attribute_value(self, view_id: str, attribute_id: str, default: Any = ..., technology_relation: str = ...) -> Any: ...
    def get_powerflow_view(self, asset_id: str) -> str | None: ...
    def get_relation_targets(self, entity_id: str, relation_id: str) -> List[str]: ...
    def get_topology_view(self, asset_id: str) -> str | None: ...
    def get_view(self, asset_id: str, view_class: str | None = ..., *, suffix: str | None = ...) -> str | None: ...
    def has_entity(self, entity_id: str) -> bool: ...
    def hydro_units_for_reservoir(self, reservoir_id: str) -> list[str]: ...
    def import_csv_by_class(self, dir_path: Union[str, pathlib.Path], create_missing_refs: bool = ...) -> Any: ...
    def import_csv_by_class_wide(self, dir_path: Union[str, pathlib.Path], *, skip_unknown_classes: bool = ..., skip_unknown_fields: bool = ...) -> Dict[str, int]: ...
    def import_csv_by_class_wide_meta(self, dir_path: str | pathlib.Path, create_missing_refs: bool = ..., strict_unknown: bool = ...) -> Any: ...
    def import_csv_hierarchical(self, dir_path: Union[str, pathlib.Path], *, create_missing_refs: bool = ..., strict_unknown: bool = ...) -> Dict[str, Any]: ...
    def import_datapackage(self, dir_path: Union[str, pathlib.Path], *, skip_unknown_classes: bool = ..., skip_unknown_fields: bool = ...) -> Dict[str, int]: ...
    def import_excel(self, path: Union[str, pathlib.Path], *, strict_unknown: bool = ...) -> Dict[str, Any]: ...
    def import_excel_flat(self, path: Union[str, pathlib.Path], *, skip_unknown_classes: bool = ..., skip_unknown_fields: bool = ...) -> Dict[str, int]: ...
    def import_frictionless(self, dir_path: Union[str, pathlib.Path], *, skip_unknown_classes: bool = ..., skip_unknown_fields: bool = ...) -> Dict[str, int]: ...
    def import_hdf5(self, path: Union[str, pathlib.Path], *, load_values: bool = ..., strict_unknown: bool = ...) -> Dict[str, Any]: ...
    def import_json(self, path: str | pathlib.Path, *, strict_unknown: bool = ...) -> Any: ...
    def import_library(self, library_yaml: str, *, namespace: str | None = ...) -> int: ...
    def import_long_csv(self, path: str | pathlib.Path, *, strict_unknown: bool = ...) -> Any: ...
    def import_parquet(self, path: Union[str, pathlib.Path], *, load_values: bool = ..., wide: bool = ...) -> Dict[str, Any]: ...
    def import_yaml(self, path: str | pathlib.Path, *, strict_unknown: bool = ...) -> Any: ...
    def import_yaml_hierarchical(self, path: str, *, strict_unknown: bool = ...) -> Any: ...
    def import_yaml_model(self, path: str | pathlib.Path, *, strict_unknown: bool = ...) -> Any: ...
    def is_class_derived_from(self, subclass_name: str, parent_name: str, inheritance: Dict[str, Union[str, List[str], None]]) -> bool: ...
    def load_analysis_profile(self, path: Union[str, Path]) -> Dict[str, Any]: ...
    def load_classes_from_yaml(self, path: Union[str, pathlib.Path]) -> Any: ...
    def obj_is_instance_of(obj: dict, parent_name: str, inheritance: dict[str, str | None], class_key: str = ...) -> bool: ...
    def print_attribute_tree(self, groups: Dict[str, List]) -> Any: ...
    def print_class_tree(self) -> Any: ...
    def reservoir_for_hydro(self, hydro_id: str) -> str | None: ...
    def resolve_inheritance(self) -> Any: ...
    def set_attr_value(self, entity_id: str, attr: str, value: Any) -> Any: ...
    def set_attribute_if_allowed(self, entity_id: str, attribute_id: str, value: Any, unit: str | None = ..., *, strict: bool = ...) -> Any: ...
    def set_technology(self, asset_id: str, technology_id: str, *, technology_class: str = ..., **technology_attrs: Any) -> bool: ...
    def summary(self, *, detailed: bool = ..., as_dict: bool = ...) -> Any: ...
    def total_capacity(self, *, asset_class: str | None = ..., region_id: str | None = ...) -> float: ...
    def unit_info(self, symbol: str) -> Any: ...
    def validate(self) -> Any: ...
    def validate_for_analysis(self, profile: Union[str, Path, Dict[str, Any]]) -> List[str]: ...
    def validate_for_analysis_or_raise(self, profile: Union[str, Path, Dict[str, Any]]) -> None: ...
    def validate_or_raise(self) -> None: ...
    def validate_relation_targets(self) -> list: ...
    def views_for_asset(self, asset_id: str) -> Dict[str, str]: ...
